x-common-env: &common-env
  EUREKA_HOST: discovery-service
  CONFIG_HOST: config-service

x-jwt-env: &jwt-env
  JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
  JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}

x-db-env: &db-env
  DB_HOST: postgres
  DB_USERNAME: athly
  DB_PASSWORD: athly

x-spring-healthcheck: &spring-healthcheck
  test: ["CMD-SHELL", "curl --fail --silent http://localhost:4321/actuator/health | grep UP || exit 1"]
  interval: 5s
  timeout: 5s
  retries: 10

x-depends-on: &depends-on
  postgres:
    condition: service_healthy
  discovery-service:
    condition: service_healthy
  config-service:
    condition: service_healthy

services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: athly
      POSTGRES_PASSWORD: athly
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U athly"]
      interval: 5s
      timeout: 5s
      retries: 5

  discovery-service:
    build:
      context: ./discovery
    container_name: discovery-service
    restart: unless-stopped
    healthcheck: *spring-healthcheck

  config-service:
    build:
      context: ./config
    container_name: config-service
    restart: unless-stopped
    healthcheck: *spring-healthcheck
    depends_on:
      discovery-service:
        condition: service_healthy
    environment: *common-env

  gateway-service:
    build:
      context: ./gateway
    container_name: gateway-service
    restart: unless-stopped
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      <<: [*common-env, *jwt-env]

  user-service:
    build:
      context: ./user
    container_name: user-service
    restart: unless-stopped
    depends_on: *depends-on
    environment:
      <<: [*common-env, *jwt-env, *db-env]
      DB_NAME: athly_user

  nutrition-service:
    build:
      context: ./nutrition
    container_name: nutrition-service
    restart: unless-stopped
    depends_on: *depends-on
    environment:
      <<: [*common-env, *jwt-env, *db-env]
      DB_NAME: athly_nutrition

  workout-service:
    build:
      context: ./workout
    container_name: workout-service
    restart: unless-stopped
    depends_on: *depends-on
    environment:
      <<: [*common-env, *jwt-env, *db-env]
      DB_NAME: athly_workout

volumes:
  postgres-data: