x-dependson-discovery: &dependson-discovery
  discovery:
    condition: service_healthy

x-dependson-configs: &dependson-configs
  configs:
    condition: service_healthy

x-service_dependson: &service_dependson
  <<: [*dependson-discovery, *dependson-configs]
  postgres:
    condition: service_healthy

x-spring_dockerfile: &spring_dockerfile
  dockerfile: ../Dockerfile

x-spring_healthcheck: &spring_healthcheck
  test: ["CMD-SHELL", "curl --fail --silent http://localhost:4321/actuator/health | grep UP || exit 1"]
  interval: 5s
  timeout: 5s
  retries: 10

x-environment-platform: &environment-platform
  DISCOVERY_URL: http://discovery:8761/eureka
  CONFIGS_URL: configserver:http://configs:8888/

x-environment-jwt: &environment-jwt
  JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
  JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}

x-environment-postgres: &environment-postgres
  DB_URL: jdbc:postgresql://postgres:5432
  DB_USERNAME: ${USERNAME}
  DB_PASSWORD: ${PASSWORD}
  DB_DRIVER: org.postgresql.Driver

x-service_environment: &service_environment
  <<: [*environment-platform, *environment-jwt, *environment-postgres]

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./.infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./.infra/grafana/provisioning:/etc/grafana/provisioning
      - ./.infra/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${PASSWORD}

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./.infra/postgres/create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  discovery:
    build:
      context: ./discovery
      <<: *spring_dockerfile
    restart: unless-stopped
    healthcheck: *spring_healthcheck

  configs:
    build:
      context: ./config
      <<: *spring_dockerfile
    restart: unless-stopped
    healthcheck: *spring_healthcheck
    depends_on: *dependson-discovery
    environment: *environment-platform

  gateway:
    build:
      context: ./gateway
      <<: *spring_dockerfile
    restart: unless-stopped
    depends_on:
      <<: [*dependson-discovery, *dependson-configs]
    ports:
      - "8080:8080"
    environment:
      <<: [*environment-platform, *environment-jwt]

  user:
    build:
      context: ./user
      <<: *spring_dockerfile
    restart: unless-stopped
    depends_on: *service_dependson
    environment:
      <<: *service_environment
      DB_NAME: users

  nutrition:
    build:
      context: ./nutrition
      <<: *spring_dockerfile
    restart: unless-stopped
    depends_on: *service_dependson
    environment:
      <<: *service_environment
      DB_NAME: nutrition

  workout:
    build:
      context: ./workout
      <<: *spring_dockerfile
    restart: unless-stopped
    depends_on: *service_dependson
    environment:
      <<: *service_environment
      DB_NAME: workouts

volumes:
  prometheus-data:
  grafana-data:
  postgres-data:
