server:
  port: 8761

management:
  server:
    port: 4321
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false