global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "config"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["configs:4321"]
  - job_name: "gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway:4321"]
  - job_name: "discovery"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["discovery:4321"]
  - job_name: "nutrition"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["nutrition:4321"]
  - job_name: "user"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user:4321"]
  - job_name: "workout"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["workout:4321"]