global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "athly-config"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["config-service:4321"]
  - job_name: "athly-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway-service:4321"]
  - job_name: "athly-discovery"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["discovery-service:4321"]
  - job_name: "athly-nutrition"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["nutrition-service:4321"]
  - job_name: "athly-user"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:4321"]
  - job_name: "athly-workout"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["workout-service:4321"]