eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL}

server:
  port: 8888

management:
  server:
    port: 4321
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: configs
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
