eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

server:
  port: 8888

management:
  server:
    port: 4321

spring:
  application:
    name: athly-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
