server:
  port: 8082
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${DB_URL}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
